from typing import Protocol

from src.models.patient import Patient


class IPatientsStorage(Protocol):
    def create(self, patient: Patient) -> Patient: ...

    def update(self, patient: Patient) -> None: ...

    def delete(self, patient_id: str) -> None: ...

    def get_patient(self, **kwargs) -> Patient | None: ...

    def get_all_patients(self) -> list[Patient]: ...
